#!/usr/bin/env bash
#
# bootstrap installs things.

# current
DOTFILES_DIR=`pwd`

# user
USER_NAME=`whoami`

# copy vimdir
DOT_VIM_DIR="${HOME}/.vim"
DOT_VIM_BUNDLE_DIR="${HOME}/.vim/bundle"
NEOBUNDLE_VIM_DIR="${DOT_VIM_BUNDLE_DIR}/neobundle.vim"

# search files
RC_PATHS=`ls ${DOTFILES_DIR}/.*rc`
PROFILE_PATHS=`ls ${DOTFILES_DIR}/.*profile`
CONF_PATHS=`ls ${DOTFILES_DIR}/.*conf`
GITCONFIG_PATH=`ls ${DOTFILES_DIR}/.gitconfig`

# module·´
symlink()
{
  while [ $# -ne 0 ]
  do
    path=$1
    file=${path##*/}
    cmd="ln -sfn ${path} ${HOME}/${file}"
    echo ${cmd}; ${cmd}

    # è§£èª¬ 2
    case $? in
        0 | 1 ) shift ;; # è§£èª¬ 3
            * ) echo ""; return 1 ;;
    esac
  done
}

# gitを最新状態にする
git pull origin master

# rcfiles
symlink ${RC_PATHS}

# profiles
symlink ${PROFILE_PATHS}
#symlink "${DOTFILES_DIR}/.emacs"

# conf
symlink ${CONF_PATHS}

# .gitconfig
symlink ${GITCONFIG_PATH}

if [ ! -s ${DOT_VIM_DIR} ] ; then 
  cmd="cp -r ${DOTFILES_DIR}/.vim ${DOT_VIM_DIR}"
  echo ${cmd}; ${cmd}
fi

if [ ! -s ${DOT_VIM_BUNDLE_DIR} ] ; then 
  mkdir -pv ${DOT_VIM_BUNDLE_DIR}
fi

if [ ! -s ${NEOBUNDLE_VIM_DIR} ] ; then 
  git clone git://github.com/Shougo/neobundle.vim ${NEOBUNDLE_VIM_DIR}
fi

# macの場合
if [ `uname` = "Darwin" ]; then
  if [ ! -s /usr/local/bin/brew ]; then
    ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
    brew bundle
  fi

  # emacs
  if [ ! -s ${HOME}/.emacs.d ]; then
    cmd="cp -r ${DOTFILES_DIR}/.emacs.d ${HOME}/.emacs.d"
    echo ${cmd}; ${cmd}
  fi
  cmd="cp ${DOTFILES_DIR}/.emacs.d/init.el ${HOME}/.emacs.d/init.el"
  echo ${cmd}; ${cmd}
  cmd="cp ${DOTFILES_DIR}/.emacs.d/Cask ${HOME}/.emacs.d/Cask"
  echo ${cmd}; ${cmd}

  cmd="cd ${DOTFILES_DIR}/.emacs.d"
  echo ${cmd}; ${cmd}

  cmd="cask install"
  echo ${cmd}; ${cmd}

  cd ~/
  sh ./.dotfiles/script/installing_ricty_on_MacOSX.sh

  go get -u github.com/nsf/gocode
  go get code.google.com/p/rog-go/exp/cmd/godef
  go get code.google.com/p/go.tools/cmd/goimports
fi
